Repository Requisitos-de-Software/2023.1-Twitch, pull requests merged in 2023-04, with the labels that each got.

#12 8 pagina inicial
  docs/index.md
  docs/planejamento/imagens/twitch_icon.png
  mkdocs.yml
Labels: documentation

#13 Req atas
  docs/atas/reuniao_1.md
  docs/atas/reuniao_2.md
  docs/atas/reuniao_3.md
Labels: documentation

#14 Primeira Versão do Rich Picture
  .gitignore
  docs/pre_rastreabilidade/assets/icons/anuncio.png
  docs/pre_rastreabilidade/assets/icons/barreira.png
  docs/pre_rastreabilidade/assets/icons/canal.png
  docs/pre_rastreabilidade/assets/icons/conteudo.png
  docs/pre_rastreabilidade/assets/icons/criador_de_conteudo.png
  docs/pre_rastreabilidade/assets/icons/empresa.png
  docs/pre_rastreabilidade/assets/icons/moderador.png
  docs/pre_rastreabilidade/assets/icons/operacao.png
  docs/pre_rastreabilidade/assets/icons/seta.png
  docs/pre_rastreabilidade/assets/icons/twitch.jpg
  docs/pre_rastreabilidade/assets/icons/usuario.png
  docs/pre_rastreabilidade/assets/versions/rich_picture_1.svg
  docs/pre_rastreabilidade/rich_picture.md
  mkdocs.yml
Labels: documentation

#16 Criando documento de Apresentações
  docs/apresentacoes.md
  mkdocs.yml
Labels: documentation

#22 Organiza o link da apresentação no iframe da github pages
  docs/apresentacoes.md
Labels: bug, entregas

#50 Criação de documento de Perfis de Usuário
  docs/elicitacao/perfis_usuario.md
Labels: documentation, pc-2
